// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using account_web.Data;

#nullable disable

namespace account_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250725031201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("account_web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 25, 11, 12, 1, 561, DateTimeKind.Local).AddTicks(3847),
                            Email = "zhang@example.com",
                            Name = "張三",
                            Phone = "0912345678",
                            UpdatedAt = new DateTime(2025, 7, 25, 11, 12, 1, 561, DateTimeKind.Local).AddTicks(3991)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 25, 11, 12, 1, 561, DateTimeKind.Local).AddTicks(4100),
                            Email = "li@example.com",
                            Name = "李四",
                            Phone = "0987654321",
                            UpdatedAt = new DateTime(2025, 7, 25, 11, 12, 1, 561, DateTimeKind.Local).AddTicks(4101)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
